# Generated by Django 4.2.6 on 2023-11-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donate_money_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_money',
            name='hide',
            field=models.BooleanField(),
        ),
    ]
