# Generated by Django 4.2.6 on 2023-11-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_donate_money_hide_donate_money_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('volun', models.CharField(max_length=30)),
                ('available', models.CharField(default='yes', max_length=3)),
            ],
        ),
    ]
