# Generated by Django 4.2.6 on 2023-11-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_volunteer_work_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrate_Together',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('celeb', models.CharField(max_length=30, null=True)),
                ('available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
            ],
        ),
    ]
