# Generated by Django 4.2.6 on 2023-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_celebrate_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrate_together',
            old_name='celeb',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='celebrate_together',
            name='available',
        ),
        migrations.AddField(
            model_name='celebrate_together',
            name='date_field',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='celebrate_together',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
